### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by wory48** [Aki0xff/Moonstone#1]
Compiling on Linux with active debug, it'd return `Floating point exception` on runtime and will dump the core stack.
![image](https://user-images.githubusercontent.com/71683721/151917012-b3bb719e-45f1-4c13-a5df-cc8209459ed7.png)

This error caused when you're dividing 0 with bigger than 0 and getting reminder. It happens when calculating xorshift and return value is 0. https://github.com/Aki0xff/Moonstone/blob/fd4c8bdf1a7b2574b2dad002148ce5a4c4e6638c/moonstone.c#L42

When changing reminder to different operator, it runs successfully.

I'm not 100% sure how it will behave on other compilers, for myself it doesn't.

**Comment by Aki0xff** [comment]
Fixed, apparently the Xorshift32 sometimes return 0
